cmake_minimum_required(VERSION 3.22)

if(NOT DEFINED DESTINATION OR NOT DEFINED TOOL_PLATFORM)
    message(FATAL_ERROR "Pass -DDESTINATION=path -DTOOL_PLATFORM=linux or windows")
endif()
if(TOOL_PLATFORM STREQUAL "linux")
    set(ctrArchive ctrtool-v1.3.0-ubuntu_x86_64.zip)
    set(ctrHash f553194b0ab2b539457160231cf5651c554e148f17ec960fae63424e82582aa8)
    set(extension "")
elseif(TOOL_PLATFORM STREQUAL "windows")
    set(ctrArchive ctrtool-v1.3.0-win_x64.zip)
    set(ctrHash 8031dff3be72d0adb250fae1f969f27627e12a89ebc6dd074a15a75f87ddc949)
    set(extension .exe)
else()
    message(FATAL_ERROR "Only linux and windows x86-64 tools are provided")
endif()

file(MAKE_DIRECTORY "${DESTINATION}/downloads")
function(FetchTool tool tag archive checksum)
    set(localArchive "${DESTINATION}/downloads/${archive}")
    message(STATUS "Fetching ${tool} from Project_CTR (${tag})")
    file(DOWNLOAD "https://github.com/3DSGuy/Project_CTR/releases/download/${tag}/${archive}"
        "${localArchive}" EXPECTED_HASH "SHA256=${checksum}" TLS_VERIFY ON SHOW_PROGRESS)
    set(extracted "${DESTINATION}/downloads/${tool}")
    file(ARCHIVE_EXTRACT INPUT "${localArchive}" DESTINATION "${extracted}")
    file(GLOB_RECURSE matches LIST_DIRECTORIES FALSE "${extracted}/${tool}${extension}")
    list(LENGTH matches matchCount)
    if(NOT matchCount EQUAL 1)
        message(FATAL_ERROR "Expected exactly one ${tool}${extension} in ${archive}")
    endif()
    list(GET matches 0 executable)
    file(COPY_FILE "${executable}" "${DESTINATION}/${tool}${extension}" ONLY_IF_DIFFERENT)
    file(CHMOD "${DESTINATION}/${tool}${extension}"
        PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
endfunction()

FetchTool(ctrtool ctrtool-v1.3.0 "${ctrArchive}" "${ctrHash}")
message(STATUS "Tool ready in ${DESTINATION}. Keep the original archive for its notices.")
